[phases.setup]
nixPkgs = ['nodejs', 'python3', 'gcc', 'gnumake']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npm run prisma:generate', 'npm run build']

[start]
cmd = 'npm run start'

[variables]
NODE_ENV = 'production'
PORT = '3000' 

[build]
  run = "nix-shell -p gcc make zlib.dev"
